# Generated by Django 4.2.2 on 2023-06-23 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Medicine',
            new_name='Medicines',
        ),
    ]
