# Generated by Django 4.2.2 on 2023-06-23 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0002_rename_medicine_medicines'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicines',
            name='expir_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='medicines',
            name='manufac_date',
            field=models.DateField(),
        ),
    ]
